name: shipment_manager
description: 出货单管理应用

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  excel: ^2.0.1
  file_picker: ^5.3.3
  sqflite: ^2.3.0
  path: ^1.8.3
  permission_handler: ^11.3.0
  share_plus: ^7.0.1
  flutter_spinkit: ^5.2.0
  open_file: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
